# Generated by Django 4.0.1 on 2022-01-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('app_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'taxi',
                'verbose_name_plural': 'taxis',
            },
        ),
    ]
