# Generated by Django 4.0.1 on 2022-01-08 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model_location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embassy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('embassy_title', models.CharField(max_length=255)),
                ('map_url', models.CharField(max_length=1000)),
                ('site_url', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embassies', to='model_location.city')),
            ],
            options={
                'verbose_name': 'embassy',
                'verbose_name_plural': 'embassies',
            },
        ),
    ]
